
---
title: "PERSONAL CHECKS"
author: "NGAIRA"
date: "2024-01-19"
output:
  
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
require(readr)
require(tidyverse)
require(magrittr)
require(ggplot2)
require(gtsummary)
require(reshape2)
require(officer)

```

# Load Data

```{r, echo=FALSE}
cema_internship_task_2023 <- read_csv("D:/NGAIRA/cema_internship_task_2023.csv")

```

# Summary 
```{r}
data<-as.data.frame(cema_internship_task_2023)
summary(data)
```

# Count the NAs

```{r}
# Count the number of missing values in each column
colSums(is.na(data))

```

# Data Visualization
```{r}
# Plot Total Dewormed by County
ggplot(data, aes(x = county, y = `Total Dewormed`)) +
  geom_bar(stat = "identity") +
  labs(title = "Total Dewormed by County", x = "County", y = "Total Dewormed") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Scatter plot of Acute Malnutrition vs. Total Dewormed
ggplot(data, aes(x = `Total Dewormed`, y = `Acute Malnutrition`)) +
  geom_point() +
  labs(title = "Scatter plot of Acute Malnutrition vs. Total Dewormed",
       x = "Total Dewormed", y = "Acute Malnutrition")

# Box plot of stunted 6-23 months by County
ggplot(data, aes(x = county, y = `stunted 6-23 months`)) +
  geom_boxplot() +
  labs(title = "Box plot of stunted 6-23 months by County",
       x = "County", y = "stunted 6-23 months") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Histogram of diarrhoea cases
ggplot(data, aes(x = `diarrhoea cases`)) +
  geom_histogram(binwidth = 100, fill = "blue", color = "black") +
  labs(title = "Histogram of diarrhoea cases",
       x = "Diarrhoea Cases", y = "Frequency")

```


